chore: disable formatter ci

diff --git a/.github/workflows/verify_formatting.yaml b/.github/workflows/verify_formatting.yaml
--- a/.github/workflows/verify_formatting.yaml
+++ b/.github/workflows/verify_formatting.yaml
@@ -18,24 +18,25 @@ jobs:
       with:
        fetch-depth: 0
        clean: true
-
-    - name: Set up Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: 22
-
-    - name: Get Prettier version from package-lock.json
-      run: |
-        PRETTIER_VERSION=$(grep -m 1 'prettier' package-lock.json | cut -d '"' -f 4 | cut -c 2-)
-        echo $PRETTIER_VERSION
     
-    - name: Check formatting
-      run: |
-        npx --yes prettier@$PRETTIER_VERSION --check --config .prettierrc .
+       # ! currently bugged! Will throw false negatives.
+    # - name: Set up Node.js
+    #   uses: actions/setup-node@v4
+    #   with:
+    #     node-version: 22
 
-    - name: Fail if formatting check failed
-      if: failure()
-      run: |
-        echo "Formatting check failed. Please format your code according to the project's Prettier configuration."
-        exit 1
+    # - name: Get Prettier version from package-lock.json
+    #   run: |
+    #     PRETTIER_VERSION=$(grep -m 1 'prettier' package-lock.json | cut -d '"' -f 4 | cut -c 2-)
+    #     echo $PRETTIER_VERSION
+    
+    # - name: Check formatting
+    #   run: |
+    #     npx --yes prettier@$PRETTIER_VERSION --check --config .prettierrc .
+
+    # - name: Fail if formatting check failed
+    #   if: failure()
+    #   run: |
+    #     echo "Formatting check failed. Please format your code according to the project's Prettier configuration."
+    #     exit 1
 
